### ISSUE TITLE
new settings dont end up getting saved to the sqlite db

### ISSUE THREAD

**Issue by storm37000** [Patcher56/PatchProtect#140]
new settings added after the server has ran the addon before dont end up getting saved to the sqlite db.

**Comment by Domii894** [comment]
Hi,
thank you very much for your contribution.
Unfortunately due to time constraints we are forced to delay reviews of bigger changes.

The proposed prop AntiSpam setting has been added with f8b338c6643f6efa0d1f5bde1992fbffb993b87d.

For the mentioned sql saving issue. I've added a comment at https://github.com/storm37000/PatchProtect/commit/e014624463a58b4117126f27741f12a5e8ad794d#r37527961.

Thanks.

**Comment by storm37000** [comment]
it being inside the load doesnt work, im talking about running server, it already created the database stuff, then add more options to the addon, then later trying to save the settings.  they wont ever be added to the database.
