### ISSUE TITLE
laser pointer issue

### ISSUE THREAD

**Issue by Bryantdl7** [Patcher56/PatchProtect#95]
[ERROR] addons/prop protection/lua/patchprotect/client/hud.lua:27: Tried to use a NULL entity!
  1. UniqueID - [C]:-1
   2. fn - addons/prop protection/lua/patchprotect/client/hud.lua:27
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

This has been confirmed to be your addon, by the ulx team and wire team.

**Comment by Domii894** [comment]
Because of the lack of information I had to investigate long time to find an issue. Hopefully I got the issue. This fix (https://github.com/Patcher56/PatchProtect/commit/91dd19ee3819870a0668b51eacb0f4a9fab9bf55) should prevent this issue.
If not, then please reopen this issue and if possible, please mention some details, when it happens and so on...
